### ISSUE TITLE
There's an issue with the level of humour in docs

### ISSUE THREAD

**Issue by TheKishPatel** [transferwise/components#115]
https://transferwise.github.io/components/

The subtitles for:

- PhoneNumberInput
- Instructions list
- Process Indicator

are not LOL-worthy enough. @Tankenstein pls fix asap.

**Comment by Tankenstein** [comment]
I'm sorry, this is unacceptable, we'll fix it ASAP. Thanks @TheKishPatel. Also let's grab beer sometime.
